typography_spectrum: 0.5769511696416885
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6502956317272037
  lightness: 0.796986430650577
  saturation: 0.42995696887373924
  rhythmicContrast: 0.6419137807097286
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14921172964386642
analytics:
  google: null
  facebook: null
  twitter: null
name: hardtruthaboutfatloss.com
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: yes you read that right
purpose: []
